### ISSUE TITLE
A first version of Postgres Database

### ISSUE THREAD

**Issue by sarjir** [sarjir/HappyPlanter-api#2]
HappyPlanter needs a database to store data regarding plants and watering! We've decided upon a Postgres database. Let's get going!

**What can go wrong?**
- I can't use a Postgres database locally
- I can't use SQL directly to query the Postgres Database
- I can't change the structure of the database

**Tasks**
- [x] Create a Postgres database locally
- [x]  Seed data to Postgres database with dummy data, does not need to represent the data that we're going to store in it later on
- [x] Try to manipulate the data structure in the Postgres database
- [x] Make an endpoint in C# to fetch data from Postgres and show in in a response
