### ISSUE TITLE
First highlevel GUI for watering schedule

### ISSUE THREAD

**Issue by sarjir** [sarjir/HappyPlanter-api#3]
The first functionality of HappyPlanter is going to be a watering schedule. This needs to be tested to see if it's good enough for its purpose

**Acceptance criteria**
- [ ] Have three tests been conducted?
- [ ] Have the test-results been documented?
- [ ] Can the test results be found from this repo?

**Tasks**
- [x] Test on Tora
- [x] Test on Amanda
- [x] Test on Anton
