### ISSUE TITLE
First endpoint to fetch all plants

### ISSUE THREAD

**Issue by sarjir** [sarjir/HappyPlanter-api#4]
### Problem
The frontend application needs somewhere to fetch data from

### Acceptance criteria
- Is there possibility to fetch all plants?
- Can you see all data for all plants?

### Tasks
- [x] Break out plant class to its own file
- [x] Remove scaffolded endpoint
- [x] Add new base URL - `/plants`
- [x] Create endpoint that returns all plants on request
